export enum Flavors {

  CHOCOLATE = 'CHOCOLATE',
  COOKIES_CREAM = 'COOKIES_CREAM',
  MORANGO = 'MORANGO',
  BAUNILHA = 'BAUNILHA',
  SEM_SABOR = 'SEM_SABOR',
  FRUTAS_VERMELHAS = 'FRUTAS_VERMELHAS',
  BLUE_ICE = 'BLUE_ICE',
  LIMAO_YUZU = 'LIMAO_YUZU',
  COTTON_CANDY = 'COTTON_CANDY',
  LIMAO = 'LIMAO',
  CITRUS = 'CITRUS',
 FRUTAS_SILVESTRES = 'FRUTAS_SILVESTRES',
  ACAI_GUARANA = 'ACAI_GUARANA'
}
